# Generated by Django 2.2.17 on 2021-05-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sekolah', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titimangsa', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Umum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran', models.IntegerField()),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=6)),
            ],
        ),
    ]
