# Generated by Django 2.2.17 on 2021-05-14 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapor',
            name='tahun_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengaturan.Umum'),
        ),
    ]
