# Generated by Django 2.2.17 on 2021-05-14 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0002_rapor_tahun_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapor',
            name='tahun_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaturan.Umum'),
        ),
    ]
