# Generated by Django 2.2.17 on 2021-01-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('kelompok', models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], max_length=2)),
                ('kkm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIS', models.CharField(max_length=9)),
                ('NISN', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('jk', models.CharField(choices=[('L', 'L'), ('P', 'P')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengetahuan', models.IntegerField()),
                ('keterampilan', models.IntegerField()),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leger.Mapel')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leger.Siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Leger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_s', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('nilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leger.Mapel')),
            ],
        ),
    ]
