# Generated by Django 2.2.17 on 2021-01-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leger',
            name='nilai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leger.Nilai'),
        ),
    ]
