# Generated by Django 2.2.17 on 2021-02-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leger', '0002_auto_20210130_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='judul',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nilai',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
