# Generated by Django 2.2.17 on 2021-04-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leger', '0003_auto_20210221_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='kelas',
            field=models.CharField(choices=[('RPL', (('XII.RPL-1', 'XII.RPL-1'), ('XII.RPL-2', 'XII.RPL-2'), ('XII.RPL-3', 'XII.RPL-3'), ('XII.RPL-4', 'XII.RPL-4'))), ('TKJ', (('XII.TKJ-1', 'XII.TKJ-1'), ('XII.TKJ-2', 'XII.TKJ-2'), ('XII.TKJ-3', 'XII.TKJ-3'), ('XII.TKJ-4', 'XII.TKJ-4')))], max_length=10, null=True),
        ),
    ]
