# Generated by Django 2.2.17 on 2021-04-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leger', '0005_auto_20210412_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='jk',
            new_name='gender',
        ),
    ]
