# Generated by Django 2.2.17 on 2021-04-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leger', '0006_auto_20210412_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapel',
            name='keterangan',
            field=models.CharField(choices=[('Muatan Nasional', 'Muatan Nasional'), ('Muatan Kewilayahan', 'Muatan Kewilayahan'), ('Muatan Peminatan dan Kejuruan', 'Muatan Peminatan dan Kejuruan')], max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='kelompok',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
    ]
