# Generated by Django 2.2.17 on 2021-04-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leger', '0009_auto_20210412_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='mapel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Mapel'),
        ),
    ]
