# Generated by Django 2.2.17 on 2021-04-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leger', '0010_auto_20210412_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nilai',
            old_name='mapel',
            new_name='mata_pelajaran',
        ),
    ]
