# Generated by Django 2.2.17 on 2021-04-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20210412_1223'),
        ('leger', '0011_auto_20210412_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='program_keahlian',
        ),
        migrations.AddField(
            model_name='nilai',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Kelas'),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Siswa'),
        ),
        migrations.DeleteModel(
            name='ProgramKeahlian',
        ),
        migrations.DeleteModel(
            name='Siswa',
        ),
    ]
