# Generated by Django 2.2.17 on 2021-05-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leger', '0012_auto_20210412_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='judul',
            field=models.CharField(choices=[('Harian', 'Harian'), ('PTS', 'PTS'), ('PAT', 'PAT'), ('PAS', 'PAS')], max_length=30, null=True),
        ),
    ]
