# Generated by Django 2.2.17 on 2021-05-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leger', '0013_auto_20210503_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='judul',
            field=models.CharField(choices=[('Harian', 'Harian'), ('PTS', 'Penilaian Tengah Semester'), ('PAS', 'Penilaian Akhir Semester'), ('PAT', 'Penilaian Akhir Tahun')], max_length=30, null=True),
        ),
    ]
