# Generated by Django 2.2.17 on 2021-05-17 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pengaturan', '0003_auto_20210514_1855'),
        ('leger', '0015_auto_20210508_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='kkm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nilai',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pengaturan.Umum'),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='siswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Rombel'),
        ),
    ]
