# Generated by Django 2.2.17 on 2021-05-17 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leger', '0017_auto_20210517_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nilai',
            name='kkm',
        ),
    ]
