# Generated by Django 2.2.17 on 2021-04-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('kelompok', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('keterangan', models.CharField(choices=[('Muatan Nasional', 'Muatan Nasional'), ('Muatan Kewilayahan', 'Muatan Kewilayahan'), ('Muatan Peminatan dan Kejuruan', 'Muatan Peminatan dan Kejuruan')], max_length=29, null=True)),
                ('kkm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('L', 'L'), ('P', 'P')], max_length=1)),
                ('level', models.CharField(choices=[('PNS', 'PNS'), ('Non-PNS', 'Non-PNS')], max_length=7)),
                ('walikelas', models.CharField(choices=[('-', '-'), ('RPL', (('XII.RPL-1', 'XII.RPL-1'), ('XII.RPL-2', 'XII.RPL-2'), ('XII.RPL-3', 'XII.RPL-3'), ('XII.RPL-4', 'XII.RPL-4'))), ('TKJ', (('XII.TKJ-1', 'XII.TKJ-1'), ('XII.TKJ-2', 'XII.TKJ-2'), ('XII.TKJ-3', 'XII.TKJ-3'), ('XII.TKJ-4', 'XII.TKJ-4')))], max_length=10)),
                ('tahun_masuk', models.DateField()),
                ('kelompok', models.CharField(choices=[('Produktif', 'Produktif'), ('Adaptif', 'Adaptif'), ('Normatif', 'Normatif')], max_length=9)),
                ('aktif', models.BooleanField(default=True)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Mapel')),
            ],
        ),
    ]
