# Generated by Django 2.2.17 on 2021-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapel',
            name='alias',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='nama',
            field=models.CharField(max_length=40),
        ),
    ]
