# Generated by Django 2.2.17 on 2021-04-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210412_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapel',
            name='kelas',
            field=models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=3, null=True),
        ),
    ]
