# Generated by Django 2.2.17 on 2021-04-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_mapel_kelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramKeahlian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='mapel',
            name='kelas',
        ),
        migrations.AlterField(
            model_name='mapel',
            name='kelompok',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], max_length=1),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='keterangan',
            field=models.CharField(choices=[('Muatan Nasional', 'Muatan Nasional'), ('Muatan Kewilayahan', 'Muatan Kewilayahan'), ('Dasar Bidang Keahlian', 'Dasar Bidang Keahlian'), ('Muatan Peminatan dan Kejuruan', 'Muatan Peminatan dan Kejuruan')], max_length=29, null=True),
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIS', models.CharField(max_length=9)),
                ('NISN', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('L', 'L'), ('P', 'P')], max_length=1)),
                ('program_keahlian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.ProgramKeahlian')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(choices=[('RPL', (('XII.RPL-1', 'XII.RPL-1'), ('XII.RPL-2', 'XII.RPL-2'), ('XII.RPL-3', 'XII.RPL-3'), ('XII.RPL-4', 'XII.RPL-4'))), ('TKJ', (('XII.TKJ-1', 'XII.TKJ-1'), ('XII.TKJ-2', 'XII.TKJ-2'), ('XII.TKJ-3', 'XII.TKJ-3'), ('XII.TKJ-4', 'XII.TKJ-4')))], max_length=10, null=True)),
                ('tahun_ajaran', models.DateField()),
                ('arsip', models.BooleanField(default=False)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Siswa')),
            ],
        ),
    ]
