# Generated by Django 2.2.17 on 2021-04-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20210412_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='programkeahlian',
            name='alias',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
