# Generated by Django 2.2.17 on 2021-04-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_programkeahlian_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='tahun_masuk',
            field=models.DateField(null=True),
        ),
    ]
