# Generated by Django 2.2.17 on 2021-04-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20210414_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='arsip',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='siswa',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='tahun_ajaran',
        ),
        migrations.AlterField(
            model_name='kelas',
            name='nama',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
