# Generated by Django 2.2.17 on 2021-04-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_auto_20210414_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rombel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('arsip', models.BooleanField(default=False)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Siswa')),
            ],
        ),
        migrations.CreateModel(
            name='GuruMapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.Mapel')),
            ],
        ),
    ]
