# Generated by Django 2.2.17 on 2021-04-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_gurumapel_rombel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rombel',
            old_name='guru',
            new_name='walikelas',
        ),
    ]
