# Generated by Django 2.2.17 on 2021-04-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20210414_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='guru',
            name='email',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='mapel',
            name='keterangan',
            field=models.CharField(choices=[('Muatan Nasional', 'Muatan Nasional'), ('Muatan Kewilayahan', 'Muatan Kewilayahan'), ('Dasar Bidang Keahlian', 'Dasar Bidang Keahlian'), ('Dasar Program Keahlian', 'Dasar Program Keahlian'), ('Muatan Peminatan dan Kejuruan', 'Muatan Peminatan dan Kejuruan')], max_length=29, null=True),
        ),
    ]
