# Generated by Django 2.2.17 on 2021-04-14 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_auto_20210415_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='walikelas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='walikelas_nama', to='master.Kelas'),
        ),
    ]
