# Generated by Django 2.2.17 on 2021-04-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_auto_20210415_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='tingkat',
            field=models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=3, null=True),
        ),
    ]
