# Generated by Django 2.2.17 on 2021-05-07 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_kelas_tingkat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='walikelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.Kelas'),
        ),
    ]
