# Generated by Django 2.2.17 on 2021-05-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_auto_20210507_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapel',
            name='nama',
            field=models.CharField(max_length=50),
        ),
    ]
