# Generated by Django 2.2.17 on 2021-05-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_auto_20210517_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapel',
            name='alokasi_waktu',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mapel',
            name='kompetensi_keahlian',
            field=models.CharField(choices=[('Semua', 'Semua'), ('TKI', 'TKI'), ('RPL', 'RPL'), ('TKJ', 'TKJ'), ('TBSM', 'TBSM')], max_length=5, null=True),
        ),
    ]
