# Generated by Django 2.2.17 on 2021-05-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_auto_20210517_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='tahun_masuk',
            field=models.DateField(null=True),
        ),
    ]
